-- Convert schema 'sql\Maximus-Schema-0.005-MySQL.sql' to 'Maximus::Schema v1.000000':;

BEGIN;

ALTER TABLE dbix_class_schema_versions ENGINE=InnoDB DEFAULT CHARACTER SET utf8;

ALTER TABLE modscope ENGINE=InnoDB DEFAULT CHARACTER SET utf8;

ALTER TABLE module ENGINE=InnoDB DEFAULT CHARACTER SET utf8;

ALTER TABLE module_dependency ENGINE=InnoDB DEFAULT CHARACTER SET utf8;

ALTER TABLE module_version ENGINE=InnoDB DEFAULT CHARACTER SET utf8;

ALTER TABLE role ENGINE=InnoDB DEFAULT CHARACTER SET utf8;

ALTER TABLE scm ENGINE=InnoDB DEFAULT CHARACTER SET utf8;

ALTER TABLE session ENGINE=InnoDB DEFAULT CHARACTER SET utf8;

ALTER TABLE user ENGINE=InnoDB DEFAULT CHARACTER SET utf8;

ALTER TABLE user_role ENGINE=InnoDB DEFAULT CHARACTER SET utf8;


COMMIT;

